<?php
/**
 * @var $this Module
 */
?>

<div>
    <img src="http://placehold.it/900x300" class="img-responsive">
    <!-- the actual blog post: title/author/date/content -->
    <h3>Developer mode <code>APP_DEVELOPER_MODE</code> is <code><?= (App::getIsDeveloperMode()) ? 'ON' : 'OFF' ?></code>
    </h3>

    <p>Exceptions will be logged if some error occurs in this mode. Also you can use <code>App::log()</code>
        function, see <code>/app/log</code> folder.</p>

    <h3>Debug Parts mode <code>APP_DEBUG_PARTS</code> is <code><?= (App::canDebugParts()) ? 'ON' : 'OFF' ?></code></h3>

    <p>In this mode you can see dotted border of each part and you can easily find where is template files. Or view page
        source code.</p>

    <h3>Interface translation mode <code>APP_TRANSLATE_INTERFACE</code>
        is <code><?= (App::canTranslateInterface()) ? 'ON' : 'OFF' ?></code></h3>

    <p>Interface translation module started, you can see gray dotted uppercase <?= $this->__('WORDS') ?>, click
        them.</p>

    <h1>Custom menu links:</h1>
    <ul>
        <li><a href="<?= $this->getUrl('about-us') ?>">Page Module Custom page view</a></li>
        <li><a href="<?= $this->getAdminUrl('login') ?>">Admin Login</a></li>
        <li><a href="<?= $this->getAdminUrl('page_new') ?>">Admin Add New Page</a></li>
    </ul>
    <hr>
    <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
    <hr>

    <hr>
    <p class="lead">Science cuts two ways, of course; its products can be used for both good and evil. But there's no
        turning back from science. The early warnings about technological dangers also come from science.</p>

    <p>You know, being a test pilot isn't always the healthiest business in the world.</p>

    <p>Cookie jelly beans soufflé icing. Gummi bears tootsie roll powder chupa chups cheesecake chocolate jelly-o
        lollipop lollipop. Halvah applicake chupa chups. Marshmallow chocolate jujubes icing lollipop gummi bears chupa
        chups pudding bonbon. Jelly beans jelly soufflé jujubes. Sesame snaps lollipop icing donut lemon drops
        soufflé.</p>

    <p>Donut caramels gingerbread. Sweet roll macaroon pastry cotton candy oat cake sesame snaps biscuit lemon drops
        dessert. Candy canes carrot cake danish carrot cake soufflé jelly chocolate cake muffin. Topping brownie donut.
        Oat cake marzipan dragée cheesecake. Donut chocolate cake jujubes tart dragée toffee.</p>

    <p>Tilefish electric knifefish salmon shark southern Dolly Varden. Pacific argentine tope golden shiner ilisha
        barreleye loosejaw catla, dogteeth tetra catfish tenpounder nase scup Ragfish brotula." Codlet brook lamprey
        pleco, Japanese eel convict cichlid titan triggerfish, plownose chimaera topminnow Black scalyfin. Walleye
        pollock, blue shark Sacramento blackfish prickleback airbreathing catfish yellowfin cutthroat trout, goby
        southern sandfish. North Pacific daggertooth dorab cepalin weever flying gurnard.</p>

    <p><strong>Placeholder text by:</strong></p>
    <ul>
        <li><a href="http://spaceipsum.com/">Space Ipsum</a></li>
        <li><a href="http://cupcakeipsum.com/">Cupcake Ipsum</a></li>
        <li><a href="http://tunaipsum.com/">Tuna Ipsum</a></li>
    </ul>
</div>


