<?php
/**
 * @var $this Module
 */
?>

<div>
    <!--<img src="http://placehold.it/900x300" class="img-responsive">-->
    <!-- the actual blog post: title/author/date/content -->
    <h3>Developer mode <code>APP_DEVELOPER_MODE</code> is <code><?= (App::getIsDeveloperMode()) ? 'ON' : 'OFF' ?></code>
    </h3>

    <p>Exceptions will be logged if some error occurs in this mode. Also you can use <code>App::log()</code>
        function, see <code>/app/log</code> folder.</p>

    <h3>Debug Parts mode <code>APP_DEBUG_PARTS</code> is <code><?= (App::canDebugParts()) ? 'ON' : 'OFF' ?></code></h3>

    <p>In this mode you can see dotted border of each part and you can easily find where is template files. Or view page
        source code.</p>

    <h3>Interface translation mode <code>APP_TRANSLATE_INTERFACE</code>
        is <code><?= (App::canTranslateInterface()) ? 'ON' : 'OFF' ?></code></h3>

    <p>Interface translation module started, you can see gray dotted uppercase <?= $this->__('WORDS') ?>, click
        them.</p>

    <h1>Custom menu links:</h1>
    <ul>
        <li><a href="<?= $this->getUrl('about-us') ?>">Page Module Custom page view</a></li>
        <li><a href="<?= $this->getAdminUrl('login') ?>">Admin Login</a></li>
        <li><a href="<?= $this->getAdminUrl('page_new') ?>">Admin Add New Page</a></li>
    </ul>
</div>


