<!-- Bootstrap core JavaScript -->
<script src="<?= $this->getThemeFileLink('js/bootstrap.js') ?>"></script>
<!-- Page Specific Plugins -->
<!--<script src="<?/*= $this->getThemeFileLink('js/raphael-min.js') */?>"></script>
<script src="<?/*= $this->getThemeFileLink('js/morris-0.4.3.min.js') */?>"></script>
<script src="<?/*= $this->getThemeFileLink('js/morris/chart-data-morris.js') */?>"></script>
<script src="<?/*= $this->getThemeFileLink('js/tablesorter/jquery.tablesorter.js') */?>"></script>
<script src="<?/*= $this->getThemeFileLink('js/tablesorter/tables.js') */?>"></script>-->