<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="<?= $this->getKeywords() ?>"/>
<meta name="description" content="<?= $this->getDescription() ?>"/>
<meta name="robots" content="*"/>
<title><?= $this->getTitle() ?></title>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/bootstrap.css') ?>" media="all"/>
<!-- Add custom CSS here -->
<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/sb-admin.css') ?>" media="all"/>
<link rel="stylesheet" href="<?= $this->getThemeFileLink('font-awesome/css/font-awesome.min.css') ?>" media="all"/>
<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/morris-0.4.3.css') ?>" media="all"/>
<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/debug.css') ?>" media="all"/>
<script src="<?= $this->getThemeFileLink('js/jquery_1.10.2.min.js') ?>"></script>