<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="<?= $this->getKeywords() ?>"/>
<meta name="description" content="<?= $this->getDescription() ?>"/>
<meta name="robots" content="*"/>
<title><?= $this->getTitle() ?></title>

<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/bootstrap.min.css') ?>" media="all"/>
<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/bootstrap-theme.css') ?>" media="all"/>
<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/debug.css') ?>" media="all"/>
<link rel="stylesheet" href="<?= $this->getThemeFileLink('font-awesome/css/font-awesome.min.css') ?>" media="all"/>
<link rel="stylesheet" href="<?= $this->getThemeFileLink('css/summernote.css') ?>" media="all"/>

<script src="<?= $this->getThemeFileLink('js/jquery.min.js') ?>" type="text/javascript"></script>