<div id="messages-area">
    <?php
    /**
     * @var $this Module
     */

    $messages = $this->getMessages();
    $has = false;
    $html = "<div class='alert alert-%s alert-dismissable'><button class='close' aria-hidden='true' data-dismiss='alert' type='button'>×</button><p>%s</p></div>";
    $block = "";
    foreach ($messages as $type => $items) {
        if (count($items)) {
            $has = true;
            $block .= sprintf($html, $type, implode('</p><p>', $items));
        }
    }
    if ($has):?>
        <?= $block ?>
    <?php endif; ?>
</div>