<?php
/**
 * @var $this Module
 */

$menus = $this->getAdminMenu();

?>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?= $this->getAdminUrl('index') ?>" style="width: 225px"><i
                class="fa fa-dashboard"></i> <?= $this->__('Admin Dashboard') ?></a>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <!-- <ul class="nav navbar-nav side-nav">
            <?php /*foreach ($menus as $action => $menuItem): */?>
                <li class="<?/*=$action*/?>">
                    <a href="<?/*= $this->getAdminUrl($action) */?>">
                        <i class="fa fa-<?/*= $action */?>"></i> <?/*= $this->__($menuItem['title']) */?>
                    </a>
                </li>
            <?php /*endforeach; */?>
        </ul>-->

        <ul class="nav navbar-nav navbar-left navbar-user">
            <?php
            $actions = $this->getAdminMenu();
            $rAction = App::getRequest()->getOrigAction();
            ?>
            <?php foreach ($actions as $group => $menu): ?>
                <li class="<?= ($group == $this->getName()) ? 'active' : '' ?> dropdown" group="<?= $group ?>">
                    <?php if (count($menu['child'])) { ?>
                        <a class="dropdown-toggle" data-toggle="dropdown"
                           href="<?= $this->getAdminUrl($menu['action']) ?>"><i class="fa <?=$menu['icon']?>"></i>
                            <?= $this->__($menu['title']) ?><b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <?php foreach ($menu['child'] as $action => $title): ?>
                                <li action="<?= $action ?>">
                                    <a href="<?= $this->getAdminUrl($action) ?>">
                                        <i class="fa"></i> <?= $this->__($title) ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php } else { ?>
                        <a href="<?= $this->getAdminUrl($menu['action']) ?>"><i class="fa <?=$menu['icon']?>"></i> <?= $this->__($menu['title']) ?></a>
                    <?php } ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <ul class="nav navbar-nav navbar-right navbar-user">
            <?php if (App::canDebugParts()): ?>
                <li>
                    <a href="#" onclick="switchPartDebug()">
                        <i class="fa fa-th-large"></i> Parts
                    </a>
                </li>
            <?php endif ?>
            <li class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith
                    <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
                    <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                    <li class="divider"></li>
                    <li><a href="<?= $this->getAdminUrl('logout') ?>"><i
                                class="fa fa-power-off"></i> <?= $this->__('Log Out') ?></a></li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>