<?php
/**
 * @var $ths Module
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->getPart('head'); ?>
</head>
<body class="<?= $this->getBodyClassName() ?>">
<div class="container">
    <div class="row" style="margin: 10px 0 ">
        <div class="col col-sm-0 visible-lg visible-md col-md-4">
            <a class="img-responsive" id="logo" href="/">
                <img class="img-responsive" src="<?= $this->getThemeFileLink('images/logo.png') ?>">
            </a>
        </div>
        <div class="col col-sm-0 col-md-4">
        </div>
        <div class="col col-sm-12 col-md-4">
            <span class="fa fa-chevron-left" style="width: 100%;margin-left: 8px">
                <?php $search=$this->__('search...')?>
                <input class="search-box" type="text" value="<?=$search?>" onblur="if(this.value.length==0)this.value='<?=$search?>'" onfocus="if(this.value=='<?=$search?>')this.value=''"><span class="fa fa-chevron-right"></span></span>
        </div>
    </div>

    <?php $this->getPart('menu/main_menu'); ?>
    <div class="row">
        <div class="col-md-8">
            <?php $this->getPart('content') ?>
        </div>
        <div class="col-md-4">
            <?php $this->getPart('sidebar'); ?>
        </div>
    </div>
    <hr>
    <?php $this->getPart('footer'); ?>
</div>
<script type="text/javascript" src="<?= $this->getThemeFileLink('js/jquery-1.8.2.min.js') ?>"></script>
<?= $this->getJs('js/bootstrap.min.js') ?>
<?php $this->getPartAll('body_before_end'); ?>
</body>
</html>
