<?php
/**
 * @var $this Module
 */
$category = $this->getParam('category');
$posts = $category->getPosts();
?>
<div>
    <?php foreach ($posts as $post): ?>

        <h1><a href="<?= $this->getUrl($post->getUrl()) ?>"><?= $post->getTitle() ?></a></h1>
        <h6>
            <small>
                <a href="#" class="tag date borderR">12 September, 2013</a>
                <a href="#" class="tag date"> <i class="fa fa-eye"></i> 20</a>
                <a href="#" class="tag date"> <i class="fa fa-comment"></i> 5</a>
                <a href="#" class="tag date borderR marginR"> <i class="fa fa-download"></i> 10</a>
                <a href="#" class="tag">Programming</a>
                <a href="#" class="tag">Data Structures</a>
                <a href="#" class="tag">Linear</a>
            </small>
        </h6>
        <div class="row">
            <div class="col-lg-4 col-sm-3 col-xs-4"><img src="/images/thumb.jpg" alt=""
                                                         class="img-thumbnail img-responsive">
            </div>
            <div class="col-lg-8 col-sm-9 col-xs-12"><?= $post->getIntro() ?>
                <div class="col-sm-2">
                    <a class="btn-sm visible-xs "
                       href="<?= $this->getUrl($post->getUrl()) ?>"><?= $this->__("Read More") ?></a>

                </div>
            </div>
        </div>

        <div class="row  hidden-xs">
            <div class="col-lg-4 col-sm-3"></div>
            <div class="col-lg-6 col-sm-7"></div>
            <div class="col-lg-2 col-sm-2">
                <a class="btn btn-primary"
                   href="<?= $this->getUrl($post->getUrl()) ?>"><?= $this->__("Read More") ?> </a>
            </div>
        </div>


        <hr>
    <?php endforeach ?>
</div>

