<?php
/**
 * sb-admin template HTML5
 **/
?>

<!DOCTYPE html>
<html lang="en">

<?php $this->getPart('head'); ?>

<body class="<?= App::getRequest()->getFullActionName() ?> <?= $this->getBodyClassName() ?>">
<div id="wrapper">
    <?php $this->getPart('navigation'); ?>
    <div id="page-wrapper">
        <div class="content-main">
            <?php $this->getPart('content_head') ?>
            <?php $this->getPart('content') ?>
        </div>
    </div>
</div>
<?php $this->getPartAll('body_before_end'); ?>
</body>
</html>
