<?php
/**
 * @var $this Module
 */
?>

<!DOCTYPE html>
<html lang="en">

<?php $this->getPart('head'); ?>
<?php $this->getPartAll('head_part'); ?>

<body class="<?= $this->getBodyClassName() ?>">
<div id="wrapper">
    <?php $this->getPart('navigation'); ?>
    <div id="page-wrapper">
        <div class="content-main">
            <div class="row">
                <div class="col-lg-12">
                    <ol class="breadcrumb">
                        <li><i class="fa fa-dashboard"></i> <?= $this->getTitle() ?></li>
                    </ol>
                    <?php $this->getPart('messages') ?>
                </div>
            </div>
            <?php $this->getPart('content') ?>
        </div>
    </div>
</div>
<?php $this->getPartAll('body_before_end'); ?>
</body>
</html>
