<?php
/**
 * @var $this Module
 */
?>

<!DOCTYPE html>
<html lang="en">

<?php $this->getPart('head'); ?>
<?php $this->getPartAll('head_part'); ?>

<body class="<?= $this->getBodyClassName() ?>">
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <?php $this->getPart('navigation'); ?>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-md-12 column">
            <?php $this->getPart('messages') ?>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-3 col-lg-2 column visible-lg visible-md">
            <div class="bs-sidebar">
                <?php $this->getPart('actions'); ?>
            </div>
        </div>
        <div class="col-md-9 col-lg-10 column">
            <?php $this->getPart('content') ?>
        </div>
    </div>
</div>
<?php $this->getPartAll('body_before_end'); ?>
</body>
</html>
