<?php
/**
 * @var $this Module
 */
$menu = $this->getMenuData('main_menu');
?>

<nav class="navbar navbar-default" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand visible-sm visible-xs " href="/">
                Code&Comments
            </a>
        </div>


        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav ">
                <?php $request = $this->getUrl(App::getRequest()->getRequestUrl()) ?>
                <?php foreach ($menu as $id => $item): ?>
                    <?php $url = $this->getUrl($item['link']) ?>
                    <li class="<?= $request == $url ? 'active' : '' ?>"><a
                            href="<?= $url ?>"><?= $item['caption'] ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>

    </div>
</nav>