<?php if (1): ?>
    <div id="part_debug_button" onclick="switchPartDebug()">Parts</div>

    <script type="text/javascript">
        $(document).ready(function(){
            fixPositions();
        })
        function switchPartDebug() {
            $('#part_debug_button').toggleClass('switched_on');
            if ($('#part_debug_button').hasClass('switched_on')) {
                fixPositions();
                $('.part_border').slideDown();
            } else {
                $('.part_border').slideUp();
            }
        }

        function fixPositions() {
            $('.part_border').each(function () {
                var next = $(this).next();
                var info = this;
                $(this)
                    .width(next.width())
                    .height(next.height())
                    .css('top', next.position().top)
                    .css('left', next.position().left)
                    .css('margin-top', next.css('margin-top'))
                    .css('margin-left', next.css('margin-left'));

            })
        }
    </script>
<?php endif; ?>