<?php
/**
 * @var $this Module
 */
?>
<div class="content-main">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading"><?=$this->__("Login to Dashboard");?></div>
                <div class="panel-body">
                    <?php $this->getPart('messages') ?>
                    <?php $this->getPart('login_form') ?>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>


