<?php
/**
 * sb-admin template HTML5
 **/
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->getPart('head'); ?>
    <?php $this->getPartAll('head_part'); ?>
</head>
<body class="<?= $this->getBodyClassName() ?>">
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <?php $this->getPart('navigation'); ?>
        </div>
    </div>
    <div class="row clearfix">
        <div id="page-wrapper">
            <?php $this->getPart('content') ?>
        </div>
    </div>
</div>
<?php $this->getPartAll('body_before_end'); ?>
</body>
</html>
