<div class="post_list">
    <div class="post_frame">
        <div class="post_menu">Batafsil</div>
        <div class="post_item">
            <h2 class="post_title">Internetda reklama va marketing</h2>

            <div class="post_img_frame">
                <img class="post_img" src="images/thumb.jpg">
            </div>
            <div class="post_data">

                <div class="post_meta">
                    <span class="date">12, March</span>
                    <span class="author">Shavkat</span>
                </div>
                <div class="post_content">
                    Internet-konferensiyasida “Internetda reklama va marketing”, “Mobil internet, dastur va
                    qurilmalar”, “Veb-resurslar” va “Texnologiya va takliflar” bosh mavzularida 28 ta
                    ma’ruza va chiqishlar tinglandi.
                    Internet-konferensiyasida “Internetda reklama va marketing”, “Mobil internet, dastur va
                    qurilmalar”, “Veb-resurslar” va “Texnologiya va takliflar” bosh mavzularida 28 ta
                    ma’ruza va chiqishlar tinglandi.
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>