<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Shavkat
 * Date: 10/23/13
 * Time: 12:08 PM
 * @var $this Module
 */

/**
 * Bu umuman boshqacha sxema deb olamiz, bu faqat post moduli uchun ishlaydi
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- we are using xhtml standard, see http://www.w3schools.com/html/html_xhtml.asp-->
<?php $this->getPart('head'); ?>
<body class="<?= App::getRequest()->getFullActionName() ?> <?= $this->getBodyClassName() ?>">
<div id="wrapper">
    <div id="page" class="noborder">
        <?php $this->getPart('content'); ?>
        <?php $this->getPart('sidebar'); ?>
    </div>

</div>
</body>
</html>