<div id="header">
    <div id="top_menu">
        <ul class="menu">
            <li class="first"><a href="/about-us">About us</a></li>
            <li><a href="#">Contacts</a></li>
            <li><a href="#">Login</a></li>
            <li class="noborder"></li>
            <li class="lang first"><a href="#">En</a></li>
            <li class="lang"><a href="#">Uz</a></li>
        </ul>
    </div>
    <h1 id="logo" class="logo">
        <a href="/">My News Blog</a>
    </h1>
    <div id="main_menu">
        <ul class="main_menu">
            <li class="first"><a href="/" class="selected">Home</a></li>
            <li><a href="#">News</a></li>
            <li><a href="#">Gallery</a></li>
            <li><a href="#">Some Page</a></li>
            <li><a href="#">Any Page</a></li>
        </ul>
    </div>
</div>