<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Shavkat
 * Date: 10/23/13
 * Time: 12:10 PM
 */

/**
 * @var $this Module
 */
?>
<head>
    <?php $this->getPart('meta') ?>

    <!-- web site icons -->
    <link rel="icon" href="<?= $this->getThemeFileLink('images/favicon.ico') ?>" type="image/x-icon"/>
    <link rel="shortcut icon" href="<?= $this->getThemeFileLink('images/favicon.ico') ?>" type="image/x-icon"/>


    <!--
        here is conditional comments, this works when we open the website using Internet Explorer below version 7,
        see http://en.wikipedia.org/wiki/Conditional_comment
    -->

    <!--[if lt IE 7]>
    <link rel="stylesheet" type="text/css" href="<?= $this->getThemeFileLink('css/styles_ie7.css')?>" media="all"/>
    <script type="text/javascript" src="<?= $this->getThemeFileLink('js/js_ie7.js')?>"></script>
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="<?= $this->getThemeFileLink('css/styles.css') ?>" media="all"/>
    <script type="text/javascript" src="<?= $this->getThemeFileLink('js/jquery-1.8.2.min.js') ?>"></script>

    <script type="text/javascript">
        //here you can write some startup scripts
        $(document).on('resize',function () {
            return fixPositions();
        }).ready(function () {
                return fixPositions();
            })
        function fixPositions() {
            $('.part_border').each(function () {
                var next = $(this).next();
                var info = this;
                $(this)
                    .width(next.width())
                    .height(next.height())
                    .css('top', next.position().top)
                    .css('left', next.position().left)
                    .css('margin-top', next.css('margin-top'))
                    .css('margin-left', next.css('margin-left'));
                $(this).click(function () {
                    $(this).css('z-index', '-1');
                })
                $(this).next().click(function () {
                    $(this).prev().css('z-index', '+1');
                })
            })
        }
    </script>
    <?php $this->getPartAll('head_part') ?>
</head>