<!-- meta tags, see http://www.w3schools.com/tags/tag_meta.asp and http://en.wikipedia.org/wiki/Meta_element-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="keywords" content="<?= $this->getKeywords() ?>"/>
<meta name="description" content="<?= $this->getDescription() ?>"/>
<meta name="robots" content="*"/>
<!-- allowed robots to index our website -->
<title><?= $this->getTitle() ?></title>
